Fix "setup.py install" referencing the correct front end script.
This commit updates setup.py to account for changes introduced by cce6e2c5.
It fixes the following error:

8<----8<----8<----8<----8<----8<----8<----
[...]
running install_scripts
running build_scripts
creating build/scripts-2.7
error: file '/path/to/ctk-cli-indexer/cli_to_json.py' does not exist
8<----8<----8<----8<----8<----8<----8<----